version: "3"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 librarySystem.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DEBUG=False
      - DB_NAME=library
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
